name: Run Python Bot

on:
  workflow_dispatch:   # manual start
  schedule:
    - cron: "0 */6 * * *"   # runs every 6 hours

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot for 6 hours
        run: |
          timeout 6h python main.py
